// src/app/panel/layout.tsx
import "@/styles/globals.css";
import type { Metadata } from "next";
import { Suspense } from "react";

// UI Imports
import Loader from "@/components/Loader";
import { PanelShell } from "@/app/layout/PanelShell";

export const metadata: Metadata = {
  title: "PICKY :: App",
  description: "Generated by create next app",
};

export default function PanelLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <div className="flex min-h-screen">
      <div className="container mx-auto flex max-w-5xl flex-col px-3">
        <Suspense fallback={<Loader />}>
          <PanelShell>{children}</PanelShell>
        </Suspense>
      </div>
    </div>
  );
}
