// src/app/panel/layout.tsx
import "@/styles/globals.css";
import type { Metadata } from "next";
import { Suspense } from "react";

// UI Imports
import { PanelHeader } from "@/app/(panel)/layout/PanelHeader";
import { PanelSide } from "@/app/(panel)/layout/PanelSide";
import { Footer } from "@/app/layout/Footer";
import Loader from "@/components/Loader";

export const metadata: Metadata = {
  title: "PICKY :: App",
  description: "Generated by create next app",
};

export default function PanelLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <div className="flex min-h-screen">
      <div className="container mx-auto flex max-w-5xl flex-col px-3">
        <PanelHeader />

        <div className="flex flex-1 gap-8">
          <PanelSide />
          <main className="flex-1">
            <Suspense fallback={<Loader />}>{children}</Suspense>
          </main>
        </div>

        <Footer />
      </div>
    </div>
  );
}
