// src/constants/content-types.ts
import {
  AppWindowIcon,
  BookIcon,
  FileTextIcon,
  FilmSlateIcon,
  GameControllerIcon,
  GlobeIcon,
  GraduationCapIcon,
  InstagramLogoIcon,
  MicrophoneIcon,
  MonitorPlayIcon,
  MusicNoteIcon,
  PenIcon,
  TelevisionSimpleIcon,
  YoutubeLogoIcon,
} from "@phosphor-icons/react/dist/ssr";

export const contentTypes = [
  { value: "APP", label: "Application", icon: AppWindowIcon },
  { value: "BAND", label: "Music Band", icon: MusicNoteIcon },
  { value: "BLOG", label: "Blog", icon: PenIcon },
  { value: "BOOK", label: "Book", icon: BookIcon },
  { value: "COURSE", label: "Course", icon: GraduationCapIcon },
  { value: "DOCUMENTARY", label: "Documentary", icon: FileTextIcon },
  { value: "INSTAGRAM", label: "Instagram", icon: InstagramLogoIcon },
  { value: "MOVIE", label: "Movie", icon: FilmSlateIcon },
  { value: "PODCAST", label: "Podcast", icon: MicrophoneIcon },
  { value: "SERIES", label: "Series", icon: TelevisionSimpleIcon },
  { value: "SONG", label: "Song", icon: MusicNoteIcon },
  { value: "TIKTOK", label: "Tiktok", icon: MonitorPlayIcon },
  { value: "VIDEO", label: "Video", icon: MonitorPlayIcon },
  { value: "WEBSITE", label: "Website", icon: GlobeIcon },
  { value: "YOUTUBE", label: "Youtube", icon: YoutubeLogoIcon },
  { value: "GAME", label: "Game", icon: GameControllerIcon },
];
