// src/app/layout.tsx
import type { Metadata } from "next";
import "@/styles/globals.css";
import { Toaster } from "sonner";
import { AuthProvider } from "@/contexts/AuthContext";

export const metadata: Metadata = {
  title: "PICKY :: App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          {children}
          <Toaster richColors duration={3000} />
        </AuthProvider>
      </body>
    </html>
  );
}
