// src/app/panel/layout.tsx
import type { Metadata } from "next";
import "@/styles/globals.css";
import { PanelSide } from "../layout/PanelSide";
import { PanelHeader } from "../layout/PanelHeader";

export const metadata: Metadata = {
  title: "PICKY :: App",
  description: "Generated by create next app",
};

export default function PanelLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <div className="flex h-screen py-10">
      <div className="flex flex-col gap-5 container max-w-5xl mx-auto h-full">
        <PanelHeader />

        <div className="flex flex-1 gap-10">
          <PanelSide />
          <main className="flex-1">{children}</main>
        </div>
      </div>
    </div>
  );
}
